stages:
  pullAskNature:
    wdir: AskNature/algolia_downloader
    cmd: python algolia-downloader.py ask_nature_paper ${ALGOLIA_APP_ID} ${ALGOLIA_APP_KEY}
    deps:
    - algolia-downloader.py
    outs:
    - ask_nature_paper.csv

  getDOIs:
    wdir: AskNature/doi_scraper
    cmd: python get_dois.py ../algolia_downloader/ask_nature_paper.csv
    deps:
    - get_dois.py
    - ../algolia_downloader/ask_nature_paper.csv
    outs:
    - doi_scraped_papers.csv

  convertAskNatureTaxonomy:
    cmd: python AskNature/taxonomy/taxonomy_converter.py AskNature/doi_scraper/doi_scraped_papers.csv AskNature/taxonomy/function_map.csv LabeledData/converted_paper
    deps:
    - AskNature/taxonomy/taxonomy_converter.py
    - AskNature/doi_scraper/doi_scraped_papers.csv
    outs:
    - AskNature/taxonomy/converted_paper.csv
    - LabeledData/converted_paper.csv

  combine:
    wdir: LabeledData
    cmd: python combine_csvs_and_jsons.py
    deps:
    - combine_csvs_and_jsons.py
    outs:
    - merged_dataframes.csv

  convert:
    wdir: LabeledData
    cmd: python convert_with_api.py merged_dataframes.csv ../Update/new_data
    deps:
    - convert_with_api.py
    - merged_dataframes.csv
    outs:
    - ../Update/new_data.json

  update:
    wdir: Update
    cmd: python update_golden.py https://raw.githubusercontent.com/nasa-petal/data-collection-and-prep/main/golden new_data ../FinalFile/new_golden
    deps:
    - update_golden.py
    - new_data.json

  validate:
    cmd: 
    - python ./FinalFile/ge_validate.py
    - zip -r ./FinalFile/Reports/report_$(date +"%Y-%m-%dT%H:%M:%S-05:00").zip ./great_expectations/uncommitted/data_docs
