name: Pipeline

# Controls when the workflow will run
on:
  # Triggers the DVC pipeline once a week at midnight
  schedule:
    - cron: "0 0 */7 * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE, and sets up Python 3.8 on the runner.
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
        
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          python -m nltk.downloader stopwords
          python -m nltk.downloader punkt
      - name: Setup Params
        run: echo "ALGOLIA_APP_ID: ${ALGOLIA_APP_ID}\n" >> params.yaml
        run: echo "ALGOLIA_APP_KEY: ${ALGOLIA_APP_KEY}\n" >> params.yaml
        run: echo "MAG_KEY: ${MAG_KEY}" >> params.yaml
      - name: Pull AskNature Papers
        run: dvc repro -f pullAskNature
      
      - name: Run DVC Pipeline
        run: dvc repro

      - name: Teardown
        run: rm params.yaml

      # Push Updates to Repo
      - name: Git Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "DVC Pipeline Trigger"
          git push
