
# This is a basic workflow to help you get started with Actions

name: Revalidate

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
        
      # Runs a single command using the runners shell
      - name: Install Dependencies
        run: |
          pip install -r validation_only_requirements.txt

      - name: Setup Params
        env:
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_APP_KEY: ${{ secrets.ALGOLIA_APP_KEY }}
          MAG_KEY: ${{ secrets.MAG_KEY_PAIR }}
        run: |
          echo "${ALGOLIA_APP_ID}" >> params.yaml
          echo "${ALGOLIA_APP_KEY}" >> params.yaml
          echo "${MAG_KEY}" >> params.yaml
          
      # Runs a set of commands using the runners shell
      - name: Run Great Expecations
        run: dvc repro validate

      # Push Updates to Repo
      - name: Git Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "DVC Pipeline Trigger"
          git push
